def Test3():
    TestedApps.Orders.Run(1, True)
    Aliases.Orders.MainForm.MainMenu.Click("File|Open...")
    OCR.Recognize(Aliases.Orders.dlgOpen.DUIViewWndClassName.Explorer_Pane.CtrlNotifySink.ShellView.Items_View.added_tbl.Name).BlockByText("added.tbl").Click()
    Aliases.Orders.dlgOpen.btnOpen.ClickButton()
    Aliases.Orders.MainForm.MainMenu.Click("Orders|New order...")
    Aliases.Orders.OrderForm.Group.Customer.Click(28, 13)
    Aliases.Orders.OrderForm.Group.Street.SetText("s")
    Aliases.Orders.OrderForm.Group.Street.SetText("sO")
    
    Aliases.Orders.OrderForm.Group.Street.SetText("sOnua")
    Aliases.Orders.OrderForm.Group.Customer.Click(60, 8)
    Aliases.Orders.OrderForm.Group.Customer.SetText("S")
    Aliases.Orders.OrderForm.Group.Customer.SetText("Sonia")
    Aliases.Orders.OrderForm.Group.Street.Click(71, 11)
    Aliases.Orders.OrderForm.Group.Street.SetText("s1")
    Aliases.Orders.OrderForm.Group.State.Click(58, 10)
    Aliases.Orders.OrderForm.Group.State.SetText("AP")
    Aliases.Orders.OrderForm.Group.City.Click(104, 10)
    Aliases.Orders.OrderForm.Group.City.SetText("TPG")
    Aliases.Orders.OrderForm.Group.Zip.Click(79, 13)
    Aliases.Orders.OrderForm.Group.Zip.SetText("54335")
    
    Aliases.Orders.OrderForm.Group.CardNo.Click(242, 7)
    Aliases.Orders.OrderForm.Group.CardNo.SetText("98765433")
    Aliases.Orders.OrderForm.ButtonOK.ClickButton()
    Aliases.Orders.MainForm.MainMenu.Click("Orders|New order...")
    Aliases.Orders.OrderForm.Group.Customer.Click(44, 11)
    Aliases.Orders.OrderForm.Group.Customer.SetText("p")
    Aliases.Orders.OrderForm.Group.Customer.SetText("pAR")
    Aliases.Orders.OrderForm.Group.Customer.SetText("pARimi")
    Aliases.Orders.OrderForm.Group.Street.Click(37, 15)
    Aliases.Orders.OrderForm.Group.Street.SetText("SR")
    Aliases.Orders.OrderForm.Group.Street.SetText("SRr")
    Aliases.Orders.OrderForm.Group.State.Click(27, 7)
    Aliases.Orders.OrderForm.Group.State.SetText("TS")
    Aliases.Orders.OrderForm.Group.City.Click(15, 11)
    Aliases.Orders.OrderForm.Group.City.SetText("H")
    Aliases.Orders.OrderForm.Group.City.SetText("Hyd")
    Aliases.Orders.OrderForm.Group.Zip.Click(49, 8)
    Aliases.Orders.OrderForm.Group.Zip.SetText("65435")
    Aliases.Orders.OrderForm.Group.CardNo.Click(181, 12)
    Aliases.Orders.OrderForm.Group.CardNo.SetText("8")
    Aliases.Orders.OrderForm.Group.CardNo.SetText("8765433")
    Aliases.Orders.OrderForm.ButtonOK.ClickButton()
    #for Editing
    Aliases.Orders.MainForm.MainMenu.Click("Orders|Edit order...")
    Aliases.Orders.OrderForm.Group.Customer.Click(36, 12)
    Aliases.Orders.OrderForm.Group.Customer.SetText("parimi")
    Aliases.Orders.OrderForm.Group.ProductNames.ClickItem("ScreenSaver")
    Aliases.Orders.OrderForm.ButtonOK.ClickButton()
    #For deleting
    Aliases.Orders.MainForm.OrdersView.DblClickItem("ggg")
    Aliases.Orders.OrderForm.ButtonCancel.ClickButton()
    Aliases.Orders.MainForm.MainMenu.Click("Orders|Delete order")
    Aliases.Orders.dlgConfirmation.btnYes.ClickButton()
    Aliases.Orders.MainForm.OrdersView.Keys("^s")
    Aliases.Orders.MainForm.Close()
